import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// Solid Icons
import {
  faMusic,
  faShield,
  faCheckCircle,
  faMapPin,
  faEnvelope,
  faPhone,
  faClock,
  faHeart,
  faGlobe,
  faChartLine,
  faPlay,
  faVideo,
  faLock,
  faUsers,
  faAward,
  faBars,
  faTimes,
  faArrowRight,
  faCheck,
  faBolt,
  faLightbulb,
  faRocket,
  faStar,
  faSpinner,
  faExclamationCircle,
  faDownload,
  faPlus,
  faMinus,
  faSearch,
  faCog,
  faSignOut,
  faUserCircle,
  faBell,
  faShoppingCart,
  faHeadphones,
  faMicrophone,
  faRecordVinyl,
  faCopyright,
  faTrophy,
  faFire,
  faThumbsUp,
  faComments,
  faShare,
  faListUl,
  faDatabase,
  faWandMagicSparkles,
  faMicrochip,
  faBrain,
  faUniversity,
  faWallet
} from '@fortawesome/free-solid-svg-icons'

// Brand Icons
import {
  faSpotify,
  faApple,
  faGoogle,
  faYoutube,
  faFacebook,
  faTwitter,
  faInstagram,
  faTiktok,
  faLinkedin,
  faGithub,
  faSoundcloud,
  faBandcamp,
  faAmazon,
  faDeezer,
  faNapster,
  faMixcloud,
  faYandex,
  faLastfm,
  faItunesNote,
  faGooglePlay,
  faAudible,
  faPaypal
} from '@fortawesome/free-brands-svg-icons'

// Add all icons to library
library.add(
  // Solid Icons
  faMusic,
  faShield,
  faCheckCircle,
  faMapPin,
  faEnvelope,
  faPhone,
  faClock,
  faHeart,
  faGlobe,
  faChartLine,
  faPlay,
  faVideo,
  faLock,
  faUsers,
  faAward,
  faBars,
  faTimes,
  faArrowRight,
  faCheck,
  faBolt,
  faLightbulb,
  faRocket,
  faStar,
  faSpinner,
  faExclamationCircle,
  faDownload,
  faPlus,
  faMinus,
  faSearch,
  faCog,
  faSignOut,
  faUserCircle,
  faBell,
  faShoppingCart,
  faHeadphones,
  faMicrophone,
  faRecordVinyl,
  faCopyright,
  faTrophy,
  faFire,
  faThumbsUp,
  faComments,
  faShare,
  faListUl,
  faDatabase,
  faWandMagicSparkles,
  faMicrochip,
  faBrain,
  faUniversity,
  faWallet,
  // Brand Icons
  faSpotify,
  faApple,
  faGoogle,
  faYoutube,
  faFacebook,
  faTwitter,
  faInstagram,
  faTiktok,
  faLinkedin,
  faGithub,
  faSoundcloud,
  faBandcamp,
  faAmazon,
  faDeezer,
  faNapster,
  faMixcloud,
  faYandex,
  faLastfm,
  faItunesNote,
  faGooglePlay,
  faAudible,
  faPaypal
)

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('FontAwesomeIcon', FontAwesomeIcon)
})
